#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir
runApplication blockMesh
runApplication buoyantHumidPimpleParcelFoam_250321

# collect the linear momentum of the cloud, the third component of which is
# the falling direction
grep '^    Linear momentum  ' log.buoyantHumidPimpleParcelFoam_250321 >momentumZ_OF.csv

# collect the mass in the system, which stays constant as long as the
# evaporation is off
grep 'Current mass in system' log.buoyantHumidPimpleParcelFoam_250321 >H2OPMass_OF.csv

#------------------------------------------------------------------------------
