#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir
runApplication blockMesh
runApplication topoSet
runApplication buoyantHumidPimpleJuliaParcelFoam_250321
runApplication buoyantHumidPimpleParcelFoam_250321

grep "momentum.z" log.buoyantHumidPimpleJuliaParcelFoam_250321 >momentumZ_ST.csv
grep "    Linear momentum" log.buoyantHumidPimpleParcelFoam_250321 >momentumZ_OF.csv

#------------------------------------------------------------------------------
