#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir
runApplication blockMesh
runApplication topoSet
runApplication buoyantHumidPimpleJuliaParcelFoam_250321
runApplication buoyantHumidPimpleParcelFoam_250321

grep "    momentum" log.buoyantHumidPimpleJuliaParcelFoam_250321 | sed -n '0~3p' >integralMomentum_ST.csv
grep "    momentum" log.buoyantHumidPimpleParcelFoam_250321 | sed -n '0~3p' >integralMomentum_OF.csv

grep "T min" log.buoyantHumidPimpleJuliaParcelFoam_250321 | sed -n '0~5p' >minmaxT_ST.csv
grep "T min" log.buoyantHumidPimpleParcelFoam_250321 | sed -n '0~5p' >minmaxT_OF.csv

grep "rhoV min" log.buoyantHumidPimpleJuliaParcelFoam_250321 | sed -n '0~5p' >minmaxrhoV_ST.csv
grep "rhoV min" log.buoyantHumidPimpleParcelFoam_250321 | sed -n '0~5p' >minmaxrhoV_OF.csv

grep 'H2O mass' log.buoyantHumidPimpleJuliaParcelFoam_250321 | sed -n '0~3p' >integralrhoV_ST.csv
grep 'H2O mass' log.buoyantHumidPimpleParcelFoam_250321 | sed -n '0~3p' >integralrhoV_OF.csv

#------------------------------------------------------------------------------
