#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir
runApplication blockMesh
runApplication topoSet
runApplication buoyantHumidPimpleJuliaParcelFoam_250321
runApplication buoyantHumidPimpleParcelFoam_250321

# collect particle temperatures
grep 'Temperature min/max' log.buoyantHumidPimpleParcelFoam_250321 >Tp_OF.csv
grep 'T = ' log.buoyantHumidPimpleJuliaParcelFoam_250321 >Tp_ST.csv

# collect particle mass OF
grep 'Current mass in system' log.buoyantHumidPimpleParcelFoam_250321 >H2OPMass_OF.csv

# collect particle diameters ST
grep dp log.buoyantHumidPimpleJuliaParcelFoam_250321 >dp_ST.csv

# collect vapour masses
grep 'H2O mass \[kg\]' log.buoyantHumidPimpleParcelFoam_250321 | sed -n '0~3p' >H2OVMass_OF.csv
grep 'H2O mass \[kg\]' log.buoyantHumidPimpleJuliaParcelFoam_250321 | sed -n '0~3p' >H2OVMass_ST.csv

#------------------------------------------------------------------------------
