#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

wclean sol/icoSTParcelFoam
wclean sol/buoyantHumidPimpleSTParcelFoam
wclean sol/buoyantHumidPimpleParcelFoam
wclean libso src/lagrangianIntermediateOpenFOAM

#------------------------------------------------------------------------------
