#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. /lib/openfoam/openfoam2406/etc/bashrc
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication $(getApplication)

#------------------------------------------------------------------------------
