#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir
runApplication blockMesh
runApplication topoSet

cp ./system/decomposeParDictST ./system/decomposeParDict
runApplication decomposePar
mv log.decomposePar log.decomposeParST
runParallel buoyantHumidPimpleJuliaParcelFoam_250321

cp ./system/decomposeParDictOF ./system/decomposeParDict
runApplication decomposePar -force
mv log.decomposePar log.decomposeParOF
runParallel buoyantHumidPimpleParcelFoam_250321

# collect continuous phase min max temperatures
grep 'T min' log.buoyantHumidPimpleParcelFoam_250321 | sed -n '0~5p' >Tcont_OF.csv
grep 'T min' log.buoyantHumidPimpleJuliaParcelFoam_250321 | sed -n '0~5p' >Tcont_ST.csv

# collect continuous phase min max vapour masses
grep "rhoV min" log.buoyantHumidPimpleParcelFoam_250321 | sed -n '0~5p' >minmaxrhoV_OF.csv
grep "rhoV min" log.buoyantHumidPimpleJuliaParcelFoam_250321 | sed -n '0~5p' >minmaxrhoV_ST.csv

# collect vapour masses
grep 'H2O mass \[kg\]' log.buoyantHumidPimpleParcelFoam_250321 | sed -n '0~3p' >H2OVMass_OF.csv
grep 'H2O mass \[kg\]' log.buoyantHumidPimpleJuliaParcelFoam_250321 | sed -n '0~3p' >H2OVMass_ST.csv


#------------------------------------------------------------------------------
