#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir
runApplication blockMesh
runApplication topoSet
runApplication buoyantHumidPimpleSTParcelFoam
runApplication buoyantHumidPimpleParcelFoam

# collect continuous phase temperatures
grep 'T min/max' log.buoyantHumidPimpleParcelFoam | sed -n '0~5p' >Tcont_OF.csv
grep 'T min/max' log.buoyantHumidPimpleSTParcelFoam | sed -n '0~5p' >Tcont_ST.csv

# collect particle temperatures
grep '    Temperature min' log.buoyantHumidPimpleParcelFoam >Tp_OF.csv
grep '^    T .*min/max' log.buoyantHumidPimpleSTParcelFoam >Tp_ST.csv

#------------------------------------------------------------------------------
