#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir
runApplication blockMesh
runApplication topoSet
runApplication buoyantHumidPimpleSTParcelFoam
runApplication buoyantHumidPimpleParcelFoam

# collect particle temperatures
grep 'Temperature min/max' log.buoyantHumidPimpleParcelFoam >Tp_OF.csv
grep '^    T  *min/max' log.buoyantHumidPimpleSTParcelFoam >Tp_ST.csv

# collect particle masses
grep 'Current mass in system' log.buoyantHumidPimpleParcelFoam >H2OPMass_OF.csv
grep 'Current mass in system' log.buoyantHumidPimpleSTParcelFoam >H2OPMass_ST.csv

# collect particle diameters ST (the reference cloud reports no diameter)
grep 'Diameter min/max' log.buoyantHumidPimpleSTParcelFoam >dp_ST.csv

# collect vapour masses
grep 'H2O mass \[kg\]' log.buoyantHumidPimpleParcelFoam | sed -n '0~3p' >H2OVMass_OF.csv
grep 'H2O mass \[kg\]' log.buoyantHumidPimpleSTParcelFoam | sed -n '0~3p' >H2OVMass_ST.csv

#------------------------------------------------------------------------------
