#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir
runApplication blockMesh
runApplication topoSet
runApplication buoyantHumidPimpleParcelFoam_250321

# collect continuous phase temperatures
grep 'T min/max' log.buoyantHumidPimpleParcelFoam_250321 | sed -n '0~5p' >Tcont_OF.csv

# collect particle temperatures
grep '    Temperature min' log.buoyantHumidPimpleParcelFoam_250321 >Tp_OF.csv

#------------------------------------------------------------------------------
